---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Rain.
--- DateTime: 2020/4/5 23:00
---
local function main()
    sum =0;
    for i=100,1,-2
    do
    print(i)
    end
end

main()


